### ISSUE TITLE
Deposit Flow: Approve Deposit pop up remains open after user completes the deposit flow

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#449] opened 2019-04-17 12:43 UTC
![video_30](https://user-images.githubusercontent.com/23660413/56288489-88a5a580-613c-11e9-874c-76aac567e406.gif)

**Comment by redben** [comment] 2019-04-18 05:54
Duplicate of #445

**Closed by redben** 2019-04-18 05:54 UTC
Labels: bug

**Comment by yuneeksehgal** [comment] 2019-04-18 12:00
Looks good now 👍
